# Generated by Django 4.2.6 on 2023-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='crypto_price',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
